name: build

on:
  pull_request:
  push:
    branches:
      - '**'
      - '!trunk'
    tags-ignore:
      - '**'

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - run: ./gradlew build

      - uses: actions/upload-artifact@v4
        with:
          name: ui-spy.zip
          path: build/distributions/ui-spy.zip
          if-no-files-found: error

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - run: docker build -t ui-spy .
        env:
          DOCKER_BUILDKIT: 1

      - name: Smoke test Docker container
        run: docker run ui-spy --help
